brew 'postgresql'
brew 'chruby'
brew 'ruby-install'
brew 'nvm'
brew 'pip'
brew 'thefuck'
brew 'ccat'
brew 'boot2docker'

cask_args appdir: '/Applications'
tap 'caskroom/cask'
cask 'google-chrome'
cask 'iterm2'
cask 'skype'
cask 'slack'
cask 'postman'
cask 'atom'
